//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 keese-ai

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingScope) DeepCopyInto(out *BindingScope) {
	*out = *in
	if in.TenantRef != nil {
		in, out := &in.TenantRef, &out.TenantRef
		*out = new(NamespacedRef)
		**out = **in
	}
	if in.WorkspaceRef != nil {
		in, out := &in.WorkspaceRef, &out.WorkspaceRef
		*out = new(NamespacedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingScope.
func (in *BindingScope) DeepCopy() *BindingScope {
	if in == nil {
		return nil
	}
	out := new(BindingScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePolicy) DeepCopyInto(out *EffectivePolicy) {
	*out = *in
	in.Tools.DeepCopyInto(&out.Tools)
	out.TokenBudget = in.TokenBudget
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePolicy.
func (in *EffectivePolicy) DeepCopy() *EffectivePolicy {
	if in == nil {
		return nil
	}
	out := new(EffectivePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveRateLimit) DeepCopyInto(out *EffectiveRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveRateLimit.
func (in *EffectiveRateLimit) DeepCopy() *EffectiveRateLimit {
	if in == nil {
		return nil
	}
	out := new(EffectiveRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveTokenBudget) DeepCopyInto(out *EffectiveTokenBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveTokenBudget.
func (in *EffectiveTokenBudget) DeepCopy() *EffectiveTokenBudget {
	if in == nil {
		return nil
	}
	out := new(EffectiveTokenBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveTools) DeepCopyInto(out *EffectiveTools) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(EffectiveRateLimit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveTools.
func (in *EffectiveTools) DeepCopy() *EffectiveTools {
	if in == nil {
		return nil
	}
	out := new(EffectiveTools)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoySpec) DeepCopyInto(out *EnvoySpec) {
	*out = *in
	if in.SecurityPolicyRef != nil {
		in, out := &in.SecurityPolicyRef, &out.SecurityPolicyRef
		*out = new(NamespacedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoySpec.
func (in *EnvoySpec) DeepCopy() *EnvoySpec {
	if in == nil {
		return nil
	}
	out := new(EnvoySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailBinding) DeepCopyInto(out *GuardrailBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailBinding.
func (in *GuardrailBinding) DeepCopy() *GuardrailBinding {
	if in == nil {
		return nil
	}
	out := new(GuardrailBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardrailBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailBindingList) DeepCopyInto(out *GuardrailBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuardrailBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailBindingList.
func (in *GuardrailBindingList) DeepCopy() *GuardrailBindingList {
	if in == nil {
		return nil
	}
	out := new(GuardrailBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardrailBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailBindingSpec) DeepCopyInto(out *GuardrailBindingSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = new(ToolsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kyverno != nil {
		in, out := &in.Kyverno, &out.Kyverno
		*out = make([]KyvernoPolicyRef, len(*in))
		copy(*out, *in)
	}
	if in.OpenFGA != nil {
		in, out := &in.OpenFGA, &out.OpenFGA
		*out = new(OpenFGASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Envoy != nil {
		in, out := &in.Envoy, &out.Envoy
		*out = new(EnvoySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RecipeHooks != nil {
		in, out := &in.RecipeHooks, &out.RecipeHooks
		*out = make([]RecipeHook, len(*in))
		copy(*out, *in)
	}
	if in.TokenBudget != nil {
		in, out := &in.TokenBudget, &out.TokenBudget
		*out = new(TokenBudget)
		**out = **in
	}
	if in.Inherit != nil {
		in, out := &in.Inherit, &out.Inherit
		*out = make([]InheritRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailBindingSpec.
func (in *GuardrailBindingSpec) DeepCopy() *GuardrailBindingSpec {
	if in == nil {
		return nil
	}
	out := new(GuardrailBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailBindingStatus) DeepCopyInto(out *GuardrailBindingStatus) {
	*out = *in
	if in.EffectivePolicy != nil {
		in, out := &in.EffectivePolicy, &out.EffectivePolicy
		*out = new(EffectivePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.LastMergeTime != nil {
		in, out := &in.LastMergeTime, &out.LastMergeTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailBindingStatus.
func (in *GuardrailBindingStatus) DeepCopy() *GuardrailBindingStatus {
	if in == nil {
		return nil
	}
	out := new(GuardrailBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InheritRef) DeepCopyInto(out *InheritRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InheritRef.
func (in *InheritRef) DeepCopy() *InheritRef {
	if in == nil {
		return nil
	}
	out := new(InheritRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KyvernoPolicyRef) DeepCopyInto(out *KyvernoPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KyvernoPolicyRef.
func (in *KyvernoPolicyRef) DeepCopy() *KyvernoPolicyRef {
	if in == nil {
		return nil
	}
	out := new(KyvernoPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef.
func (in *NamespacedRef) DeepCopy() *NamespacedRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGASpec) DeepCopyInto(out *OpenFGASpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(NamespacedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGASpec.
func (in *OpenFGASpec) DeepCopy() *OpenFGASpec {
	if in == nil {
		return nil
	}
	out := new(OpenFGASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit) DeepCopyInto(out *RateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit.
func (in *RateLimit) DeepCopy() *RateLimit {
	if in == nil {
		return nil
	}
	out := new(RateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecipeHook) DeepCopyInto(out *RecipeHook) {
	*out = *in
	out.ServiceRef = in.ServiceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecipeHook.
func (in *RecipeHook) DeepCopy() *RecipeHook {
	if in == nil {
		return nil
	}
	out := new(RecipeHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRef) DeepCopyInto(out *ServiceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRef.
func (in *ServiceRef) DeepCopy() *ServiceRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudget) DeepCopyInto(out *TokenBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudget.
func (in *TokenBudget) DeepCopy() *TokenBudget {
	if in == nil {
		return nil
	}
	out := new(TokenBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsSpec) DeepCopyInto(out *ToolsSpec) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsSpec.
func (in *ToolsSpec) DeepCopy() *ToolsSpec {
	if in == nil {
		return nil
	}
	out := new(ToolsSpec)
	in.DeepCopyInto(out)
	return out
}
