apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keese
  name: keese-observability-tokenbudget-editor-role
rules:
- apiGroups:
  - observability.operator.keese.ai
  resources:
  - tokenbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.operator.keese.ai
  resources:
  - tokenbudgets/status
  verbs:
  - get
