apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keese
  name: keese-recipe-recipesource-viewer-role
rules:
- apiGroups:
  - recipe.operator.keese.ai
  resources:
  - recipesources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - recipe.operator.keese.ai
  resources:
  - recipesources/status
  verbs:
  - get
