//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRAApproval) DeepCopyInto(out *CRAApproval) {
	*out = *in
	in.ApprovedAt.DeepCopyInto(&out.ApprovedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRAApproval.
func (in *CRAApproval) DeepCopy() *CRAApproval {
	if in == nil {
		return nil
	}
	out := new(CRAApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRAScope) DeepCopyInto(out *CRAScope) {
	*out = *in
	if in.NATSSubjects != nil {
		in, out := &in.NATSSubjects, &out.NATSSubjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.A2ARoles != nil {
		in, out := &in.A2ARoles, &out.A2ARoles
		*out = make([]A2ARole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRAScope.
func (in *CRAScope) DeepCopy() *CRAScope {
	if in == nil {
		return nil
	}
	out := new(CRAScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapsuleTenantRef) DeepCopyInto(out *CapsuleTenantRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapsuleTenantRef.
func (in *CapsuleTenantRef) DeepCopy() *CapsuleTenantRef {
	if in == nil {
		return nil
	}
	out := new(CapsuleTenantRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossNamespaceObjectRef) DeepCopyInto(out *CrossNamespaceObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossNamespaceObjectRef.
func (in *CrossNamespaceObjectRef) DeepCopy() *CrossNamespaceObjectRef {
	if in == nil {
		return nil
	}
	out := new(CrossNamespaceObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossTenantAgreement) DeepCopyInto(out *CrossTenantAgreement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossTenantAgreement.
func (in *CrossTenantAgreement) DeepCopy() *CrossTenantAgreement {
	if in == nil {
		return nil
	}
	out := new(CrossTenantAgreement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrossTenantAgreement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossTenantAgreementList) DeepCopyInto(out *CrossTenantAgreementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CrossTenantAgreement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossTenantAgreementList.
func (in *CrossTenantAgreementList) DeepCopy() *CrossTenantAgreementList {
	if in == nil {
		return nil
	}
	out := new(CrossTenantAgreementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrossTenantAgreementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossTenantAgreementSpec) DeepCopyInto(out *CrossTenantAgreementSpec) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.To.DeepCopyInto(&out.To)
	in.Scope.DeepCopyInto(&out.Scope)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossTenantAgreementSpec.
func (in *CrossTenantAgreementSpec) DeepCopy() *CrossTenantAgreementSpec {
	if in == nil {
		return nil
	}
	out := new(CrossTenantAgreementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossTenantAgreementStatus) DeepCopyInto(out *CrossTenantAgreementStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastReconcileTime.DeepCopyInto(&out.LastReconcileTime)
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = make([]CRAApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkspaceSnapshot != nil {
		in, out := &in.WorkspaceSnapshot, &out.WorkspaceSnapshot
		*out = make([]WorkspaceSnapshotEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossTenantAgreementStatus.
func (in *CrossTenantAgreementStatus) DeepCopy() *CrossTenantAgreementStatus {
	if in == nil {
		return nil
	}
	out := new(CrossTenantAgreementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectRef) DeepCopyInto(out *LocalObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectRef.
func (in *LocalObjectRef) DeepCopy() *LocalObjectRef {
	if in == nil {
		return nil
	}
	out := new(LocalObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryBudget) DeepCopyInto(out *RetryBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryBudget.
func (in *RetryBudget) DeepCopy() *RetryBudget {
	if in == nil {
		return nil
	}
	out := new(RetryBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantEndpoint) DeepCopyInto(out *TenantEndpoint) {
	*out = *in
	out.TenantRef = in.TenantRef
	if in.WorkspaceSelector != nil {
		in, out := &in.WorkspaceSelector, &out.WorkspaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantEndpoint.
func (in *TenantEndpoint) DeepCopy() *TenantEndpoint {
	if in == nil {
		return nil
	}
	out := new(TenantEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantOIDCConfig) DeepCopyInto(out *TenantOIDCConfig) {
	*out = *in
	if in.AllowedProviders != nil {
		in, out := &in.AllowedProviders, &out.AllowedProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantOIDCConfig.
func (in *TenantOIDCConfig) DeepCopy() *TenantOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(TenantOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSecurityConfig) DeepCopyInto(out *TenantSecurityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSecurityConfig.
func (in *TenantSecurityConfig) DeepCopy() *TenantSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(TenantSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	if in.CapsuleTenantRef != nil {
		in, out := &in.CapsuleTenantRef, &out.CapsuleTenantRef
		*out = new(CapsuleTenantRef)
		**out = **in
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AdminSubjects != nil {
		in, out := &in.AdminSubjects, &out.AdminSubjects
		*out = make([]TenantSubject, len(*in))
		copy(*out, *in)
	}
	if in.DefaultGuardrailBindings != nil {
		in, out := &in.DefaultGuardrailBindings, &out.DefaultGuardrailBindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenBudgetRef != nil {
		in, out := &in.TokenBudgetRef, &out.TokenBudgetRef
		*out = new(CrossNamespaceObjectRef)
		**out = **in
	}
	if in.CredentialPoolRef != nil {
		in, out := &in.CredentialPoolRef, &out.CredentialPoolRef
		*out = new(CrossNamespaceObjectRef)
		**out = **in
	}
	if in.DefaultWorkspaceQuota != nil {
		in, out := &in.DefaultWorkspaceQuota, &out.DefaultWorkspaceQuota
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(TenantOIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(TenantSecurityConfig)
		**out = **in
	}
	if in.DefaultRetryBudget != nil {
		in, out := &in.DefaultRetryBudget, &out.DefaultRetryBudget
		*out = new(RetryBudget)
		**out = **in
	}
	if in.ArtifactStoreRef != nil {
		in, out := &in.ArtifactStoreRef, &out.ArtifactStoreRef
		*out = new(CrossNamespaceObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastReconcileTime.DeepCopyInto(&out.LastReconcileTime)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSubject) DeepCopyInto(out *TenantSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSubject.
func (in *TenantSubject) DeepCopy() *TenantSubject {
	if in == nil {
		return nil
	}
	out := new(TenantSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSnapshotEntry) DeepCopyInto(out *WorkspaceSnapshotEntry) {
	*out = *in
	in.SnapshotAt.DeepCopyInto(&out.SnapshotAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSnapshotEntry.
func (in *WorkspaceSnapshotEntry) DeepCopy() *WorkspaceSnapshotEntry {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSnapshotEntry)
	in.DeepCopyInto(out)
	return out
}
