apiVersion: policy.keese.ai/v1alpha1
kind: TokenBudget
metadata:
  labels:
    app.kubernetes.io/name: keese
    app.kubernetes.io/managed-by: kustomize
  name: tokenbudget-sample
spec:
  # TODO(user): Add fields here
