apiVersion: recipe.operator.keese.ai/v1alpha1
kind: RecipeSource
metadata:
  labels:
    app.kubernetes.io/name: keese
    app.kubernetes.io/managed-by: kustomize
  name: recipesource-sample
spec:
  # TODO(user): Add fields here
