# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 keese-ai
# Minimal WorkflowRun sample.
apiVersion: workflow.operator.keese.ai/v1alpha1
kind: WorkflowRun
metadata:
  labels:
    app.kubernetes.io/name: keese
    app.kubernetes.io/managed-by: kustomize
    keese.ai/managed: "true"
  name: workflowrun-sample
spec:
  workspaceRef:
    name: my-workspace
  workflowRef:
    name: workflow-sample
  retryBudget: 5
