# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 keese-ai
# Minimal Workflow sample — one template, no triggers.
apiVersion: workflow.operator.keese.ai/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: keese
    app.kubernetes.io/managed-by: kustomize
    keese.ai/managed: "true"
  name: workflow-sample
spec:
  entrypoint: hello
  templates:
    - name: hello
      image: alpine:3.18
      command: [echo]
      args: ["hello from keese"]
