//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A2AConfig) DeepCopyInto(out *A2AConfig) {
	*out = *in
	if in.PeerAuth != nil {
		in, out := &in.PeerAuth, &out.PeerAuth
		*out = new(A2APeerAuth)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(A2AScope)
		**out = **in
	}
	if in.WorkspaceSA != nil {
		in, out := &in.WorkspaceSA, &out.WorkspaceSA
		*out = new(WorkspaceSAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MutualTLS != nil {
		in, out := &in.MutualTLS, &out.MutualTLS
		*out = new(MutualTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2AConfig.
func (in *A2AConfig) DeepCopy() *A2AConfig {
	if in == nil {
		return nil
	}
	out := new(A2AConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPConfig) DeepCopyInto(out *MCPConfig) {
	*out = *in
	out.McpRouteRef = in.McpRouteRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPConfig.
func (in *MCPConfig) DeepCopy() *MCPConfig {
	if in == nil {
		return nil
	}
	out := new(MCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutualTLSConfig) DeepCopyInto(out *MutualTLSConfig) {
	*out = *in
	out.CertificateRef = in.CertificateRef
	if in.AclRef != nil {
		in, out := &in.AclRef, &out.AclRef
		*out = new(NamespacedObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutualTLSConfig.
func (in *MutualTLSConfig) DeepCopy() *MutualTLSConfig {
	if in == nil {
		return nil
	}
	out := new(MutualTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSConfig) DeepCopyInto(out *NATSConfig) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.AckPolicy != nil {
		in, out := &in.AckPolicy, &out.AckPolicy
		*out = new(AckPolicy)
		**out = **in
	}
	if in.MaxDeliver != nil {
		in, out := &in.MaxDeliver, &out.MaxDeliver
		*out = new(int32)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(NATSTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StreamConfig != nil {
		in, out := &in.StreamConfig, &out.StreamConfig
		*out = new(NATSStreamConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSConfig.
func (in *NATSConfig) DeepCopy() *NATSConfig {
	if in == nil {
		return nil
	}
	out := new(NATSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSStreamConfig) DeepCopyInto(out *NATSStreamConfig) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSStreamConfig.
func (in *NATSStreamConfig) DeepCopy() *NATSStreamConfig {
	if in == nil {
		return nil
	}
	out := new(NATSStreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSTLSConfig) DeepCopyInto(out *NATSTLSConfig) {
	*out = *in
	if in.CertificateRef != nil {
		in, out := &in.CertificateRef, &out.CertificateRef
		*out = new(NamespacedObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSTLSConfig.
func (in *NATSTLSConfig) DeepCopy() *NATSTLSConfig {
	if in == nil {
		return nil
	}
	out := new(NATSTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectRef) DeepCopyInto(out *NamespacedObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectRef.
func (in *NamespacedObjectRef) DeepCopy() *NamespacedObjectRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconnectBackoff) DeepCopyInto(out *ReconnectBackoff) {
	*out = *in
	if in.Multiplier != nil {
		in, out := &in.Multiplier, &out.Multiplier
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconnectBackoff.
func (in *ReconnectBackoff) DeepCopy() *ReconnectBackoff {
	if in == nil {
		return nil
	}
	out := new(ReconnectBackoff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StdioConfig) DeepCopyInto(out *StdioConfig) {
	*out = *in
	if in.InboundQueueDepth != nil {
		in, out := &in.InboundQueueDepth, &out.InboundQueueDepth
		*out = new(int32)
		**out = **in
	}
	if in.OutboundQueueDepth != nil {
		in, out := &in.OutboundQueueDepth, &out.OutboundQueueDepth
		*out = new(int32)
		**out = **in
	}
	if in.ReconnectBufferBytes != nil {
		in, out := &in.ReconnectBufferBytes, &out.ReconnectBufferBytes
		*out = new(int64)
		**out = **in
	}
	if in.ReconnectRetries != nil {
		in, out := &in.ReconnectRetries, &out.ReconnectRetries
		*out = new(int32)
		**out = **in
	}
	if in.ReconnectBackoff != nil {
		in, out := &in.ReconnectBackoff, &out.ReconnectBackoff
		*out = new(ReconnectBackoff)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StdioConfig.
func (in *StdioConfig) DeepCopy() *StdioConfig {
	if in == nil {
		return nil
	}
	out := new(StdioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Transport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportList) DeepCopyInto(out *TransportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Transport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportList.
func (in *TransportList) DeepCopy() *TransportList {
	if in == nil {
		return nil
	}
	out := new(TransportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportSpec) DeepCopyInto(out *TransportSpec) {
	*out = *in
	if in.NATS != nil {
		in, out := &in.NATS, &out.NATS
		*out = new(NATSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.A2A != nil {
		in, out := &in.A2A, &out.A2A
		*out = new(A2AConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPConfig)
		**out = **in
	}
	if in.Stdio != nil {
		in, out := &in.Stdio, &out.Stdio
		*out = new(StdioConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportSpec.
func (in *TransportSpec) DeepCopy() *TransportSpec {
	if in == nil {
		return nil
	}
	out := new(TransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportStatus) DeepCopyInto(out *TransportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportStatus.
func (in *TransportStatus) DeepCopy() *TransportStatus {
	if in == nil {
		return nil
	}
	out := new(TransportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSAConfig) DeepCopyInto(out *WorkspaceSAConfig) {
	*out = *in
	if in.AuthzTupleCheck != nil {
		in, out := &in.AuthzTupleCheck, &out.AuthzTupleCheck
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSAConfig.
func (in *WorkspaceSAConfig) DeepCopy() *WorkspaceSAConfig {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSAConfig)
	in.DeepCopyInto(out)
	return out
}
