//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGate) DeepCopyInto(out *FeatureGate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGate.
func (in *FeatureGate) DeepCopy() *FeatureGate {
	if in == nil {
		return nil
	}
	out := new(FeatureGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureGate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGateList) DeepCopyInto(out *FeatureGateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeatureGate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGateList.
func (in *FeatureGateList) DeepCopy() *FeatureGateList {
	if in == nil {
		return nil
	}
	out := new(FeatureGateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureGateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGateSpec) DeepCopyInto(out *FeatureGateSpec) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(bool)
		**out = **in
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGateSpec.
func (in *FeatureGateSpec) DeepCopy() *FeatureGateSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureGateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGateStatus) DeepCopyInto(out *FeatureGateStatus) {
	*out = *in
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGateStatus.
func (in *FeatureGateStatus) DeepCopy() *FeatureGateStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureGateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricebookRef) DeepCopyInto(out *PricebookRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricebookRef.
func (in *PricebookRef) DeepCopy() *PricebookRef {
	if in == nil {
		return nil
	}
	out := new(PricebookRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudget) DeepCopyInto(out *TokenBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudget.
func (in *TokenBudget) DeepCopy() *TokenBudget {
	if in == nil {
		return nil
	}
	out := new(TokenBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetList) DeepCopyInto(out *TokenBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TokenBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetList.
func (in *TokenBudgetList) DeepCopy() *TokenBudgetList {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetScope) DeepCopyInto(out *TokenBudgetScope) {
	*out = *in
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(TokenBudgetScopeRef)
		**out = **in
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(TokenBudgetScopeRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetScope.
func (in *TokenBudgetScope) DeepCopy() *TokenBudgetScope {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetScopeRef) DeepCopyInto(out *TokenBudgetScopeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetScopeRef.
func (in *TokenBudgetScopeRef) DeepCopy() *TokenBudgetScopeRef {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetScopeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetSpec) DeepCopyInto(out *TokenBudgetSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make([]TokenLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PricebookRef != nil {
		in, out := &in.PricebookRef, &out.PricebookRef
		*out = new(PricebookRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetSpec.
func (in *TokenBudgetSpec) DeepCopy() *TokenBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetStatus) DeepCopyInto(out *TokenBudgetStatus) {
	*out = *in
	if in.ConsumedCurrent != nil {
		in, out := &in.ConsumedCurrent, &out.ConsumedCurrent
		*out = make([]TokenUsageEntry, len(*in))
		copy(*out, *in)
	}
	if in.ConsumedPrevious != nil {
		in, out := &in.ConsumedPrevious, &out.ConsumedPrevious
		*out = make([]TokenUsageEntry, len(*in))
		copy(*out, *in)
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetStatus.
func (in *TokenBudgetStatus) DeepCopy() *TokenBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenLimit) DeepCopyInto(out *TokenLimit) {
	*out = *in
	if in.InputTokens != nil {
		in, out := &in.InputTokens, &out.InputTokens
		*out = new(int64)
		**out = **in
	}
	if in.OutputTokens != nil {
		in, out := &in.OutputTokens, &out.OutputTokens
		*out = new(int64)
		**out = **in
	}
	if in.TotalTokens != nil {
		in, out := &in.TotalTokens, &out.TotalTokens
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenLimit.
func (in *TokenLimit) DeepCopy() *TokenLimit {
	if in == nil {
		return nil
	}
	out := new(TokenLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenUsageEntry) DeepCopyInto(out *TokenUsageEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenUsageEntry.
func (in *TokenUsageEntry) DeepCopy() *TokenUsageEntry {
	if in == nil {
		return nil
	}
	out := new(TokenUsageEntry)
	in.DeepCopyInto(out)
	return out
}
