# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 keese-ai
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keese-cosign-webhook
  namespace: keese-system
  labels:
    app.kubernetes.io/name: keese-cosign-webhook
    app.kubernetes.io/component: admission
